### ISSUE TITLE
Ambiguous and physical motion stimulus duration 

### ISSUE THREAD

**Issue by 27-apizzuti** [MSchnei/motion_quartet_scripts#1]
Hi @MSchnei, 

I am planning to use this repository for a new experiment. Thank you very much for the available codes and the detailed explanation in the Supplementary Information Appendix provided for [Columnar clusters in the human motion complex reflect consciously perceived motion axis](https://www.pnas.org/doi/10.1073/pnas.1814504116). I have a small question regarding the duration of the ambiguous and physical stimulus. For the ambiguous case, in SI Appendix at line 67 the reported duration is 40s, while in the `ambiguous.py` script at line 111 the reported duration is 80s. For the physical case, I found the same discrepancy between line 73 of SI Appendix and the `unambiguous.py` script. Is the correct duration for both stimuli 80s? 

Thank you in advance.

**Comment by MSchnei** [comment]
Hi @27-apizzuti,

Thank you for your question.
I would recommend you to rely on the values in the code (rather than the ones on the Supplementary Information).

Best,
Marian
